// Generated by Xata Codegen 0.22.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "todo-list",
    columns: [
      { name: "Task", type: "text", notNull: true, defaultValue: "" },
      { name: "isDone", type: "bool" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type TodoList = InferredTypes["todo-list"];
export type TodoListRecord = TodoList & XataRecord;

export type DatabaseSchema = {
  "todo-list": TodoListRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://Todo-App-5gqroj.us-east-1.xata.sh/db/todo-app",
  enableBrowser: true,
  apiKey: 'xau_mTVXCHBPilru8a0SUie6oMbuxsYBzklM1',
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
